# Generated by Django 5.0.7 on 2024-07-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eservice', '0002_alter_newsletter_clients_alter_newsletter_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
