# Generated by Django 5.0.7 on 2024-07-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eservice', '0003_alter_client_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemptsnewsletter',
            options={'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылки'},
        ),
    ]
