# Generated by Django 5.0.7 on 2024-07-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eservice', '0004_alter_attemptsnewsletter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='period',
            field=models.CharField(choices=[('DISABLE', 'Отключено'), ('EVERY_DAY', 'Ежедневно'), ('EVERY_WEEK', 'Еженедельно'), ('EVERY_MONTH', 'Ежемесячно')], default='DISABLE', max_length=30, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создана'), ('RUNNED', 'Запущена'), ('COMPLETED', 'Завершена')], default='CREATED', max_length=30, verbose_name='статус рассылки'),
        ),
    ]
