# Generated by Django 5.0.7 on 2024-08-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eservice', '0005_alter_newsletter_period_alter_newsletter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='date_time_last_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время последней отправки рассылки'),
        ),
    ]
