# Generated by Django 5.0.7 on 2024-08-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eservice', '0006_newsletter_date_time_last_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='date_time_next_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время следующей рассылки'),
        ),
    ]
