# Generated by Django 5.0.7 on 2024-08-07 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eservice", "0009_client_owner_message_owner_newsletter_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attemptsnewsletter",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца товара",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="AttemptsNewsletters",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец товара",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца товара",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Clients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец товара",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца товара",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец товара",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца товара",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Newsletters",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец товара",
            ),
        ),
    ]
