# Generated by Django 5.0.7 on 2024-08-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eservice", "0011_alter_attemptsnewsletter_owner_alter_client_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attemptsnewsletter",
            options={
                "permissions": [("manager", "Доступ менеджера")],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [("manager", "Доступ менеджера")],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("manager", "Доступ менеджера")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [("manager", "Доступ менеджера")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
